---
- name: check and create application directory
  file: path="{{ application_dir }}" state=directory owner={{ ansible_env.SUDO_USER }} group={{ ansible_env.SUDO_USER }} mode=0755
  tags:
    - server
    - local
