src_dir: /usr/local/src
install_path: /usr/local
command_path: /usr/local/bin

# ミドルウェアバージョン
git_version: 2.14.2
ruby_version: 2.4.1
java_version: 1.8.0
ant_version: 1.10.1
gradle_version: 4.2.1
mybatis_migrations_version: 3.2.1

# MySQL
mysql_log_dir: /var/log/mysql
mysql_root_password: root
mysql_admin_password: admin
mysql_first_db_name: test

# JDBC
jdbc_mysql_version: 5.1.44
