---
# rootで実行するロールです
- name: copy mongodb-org-3.6.repo
  copy: src=mongodb-org-3.6.repo dest=/etc/yum.repos.d/ mode=0644
  tags:
    - mongodb

- name: install mongodb
  yum: name=mongodb-org state=present
  tags:
    - mongodb
    - install
  notify: restart MongoDB

- name: start MongoDB service
  service: name=mongod enabled=yes state=started
  tags:
    - mongodb
    - start
