# 先にmysql/dbタスクを実施すること
- name: create mysql user
  mysql_user: name={{ item.name }} password={{ item.pass }} host={{ item.host }} priv=*.*:ALL,GRANT state=present
  with_items:
    - {name: "admin", pass: "{{ mysql_admin_password }}", host: "%"}
    - {name: "admin", pass: "{{ mysql_admin_password }}", host: "localhost"}
    - {name: "admin", pass: "{{ mysql_admin_password }}", host: "127.0.0.1"}
  tags:
    - mysql
    - user
