---
- name: Install yum-utils
  yum:
    name: yum-utils
  tags:
    - docker
    - install

- name: Set up the Docker CE repository on CentOS
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  tags:
    - docker

- name: Install the latest version of Docker CE on CentOS
  yum:
    name: docker-ce
    update_cache: yes
  tags:
    - docker
    - install

- name: run docker
  systemd: name=docker state=started daemon_reload=yes enabled=yes
  tags: 
    - docker
    - start
